/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang.pom;

import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;
import org.xtext.example.mydsl.idea.lang.T1Language;

public class T1PomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {

	public T1PomDeclarationSearcher() {
		super(T1Language.INSTANCE);
	}
}
