/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import org.jetbrains.annotations.NotNull;
import org.xtext.example.mydsl.idea.lang.T1Language;

public class T1SyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
	@NotNull
	protected SyntaxHighlighter createHighlighter() {
		return T1Language.INSTANCE.getInstance(SyntaxHighlighter.class);
	}
}
