/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.T1RuntimeModule;
import org.xtext.example.mydsl.T1StandaloneSetup;
import org.xtext.example.mydsl.ide.T1IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class T1IdeSetup extends T1StandaloneSetup {
  @Override
  public Injector createInjector() {
    T1RuntimeModule _t1RuntimeModule = new T1RuntimeModule();
    T1IdeModule _t1IdeModule = new T1IdeModule();
    return Guice.createInjector(Modules2.mixin(_t1RuntimeModule, _t1IdeModule));
  }
}
