/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class T1StandaloneSetup extends T1StandaloneSetupGenerated {

	def static void doSetup() {
		new T1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
