/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class T1IdeaModule extends AbstractT1IdeaModule {
}
