/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class T1IdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new T1StandaloneSetupIdea().createInjector
	}

}
