/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractT1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class T1RuntimeModule extends AbstractT1RuntimeModule {
}
