/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.T1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class T1StandaloneSetup extends T1StandaloneSetupGenerated {
  public static void doSetup() {
    new T1StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
