/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl.T1RuntimeModule
import org.xtext.example.mydsl.T1StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class T1IdeSetup extends T1StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new T1RuntimeModule, new T1IdeModule))
	}
	
}
