/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.highlighting;

import org.xtext.example.mydsl.idea.highlighting.T1BaseColorSettingsPage;

@SuppressWarnings("all")
public class T1ColorSettingsPage extends T1BaseColorSettingsPage {
}
