/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.xtext.example.mydsl.idea.lang.T1Language

class T1CompletionContributor extends AbstractT1CompletionContributor {
	new() {
		this(T1Language.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
