/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.completion;

import org.xtext.example.mydsl.idea.completion.AbstractT1CompletionContributor;

@SuppressWarnings("all")
public class T1CompletionContributor extends AbstractT1CompletionContributor {
  public T1CompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor T1CompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public T1CompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
