/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang;

import org.xtext.example.mydsl.idea.lang.AbstractT1FileType;

@SuppressWarnings("all")
public class T1FileType extends AbstractT1FileType {
  public final static T1FileType INSTANCE = new T1FileType();
  
  public T1FileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(T1Language) is undefined");
  }
}
