/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.xtext.example.mydsl.idea.lang.T1FileType;
import org.xtext.example.mydsl.idea.lang.T1Language;

public final class T1FileImpl extends BaseXtextFile {

	public T1FileImpl(FileViewProvider viewProvider) {
		super(viewProvider, T1Language.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return T1FileType.INSTANCE;
	}
}
