/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang


class T1FileType extends AbstractT1FileType {
	public static final T1FileType INSTANCE = new T1FileType()
	
	new() {
		super(T1Language.INSTANCE)
	}
}
