/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class T1FacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
