/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractT1CompletionContributor extends TerminalsCompletionContributor {
	public AbstractT1CompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
