/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class T1FileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(T1FileType.INSTANCE, AbstractT1FileType.DEFAULT_EXTENSION);
	}

}
