/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class T1Language extends AbstractXtextLanguage {

	public static final T1Language INSTANCE = new T1Language();

	private T1Language() {
		super("org.xtext.example.mydsl.T1");
	}

}
