/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import org.eclipse.xtext.idea.facet.AbstractFacetType;
import org.xtext.example.mydsl.idea.lang.T1Language;

public class T1FacetType extends AbstractFacetType<T1FacetConfiguration> {

	public static final FacetTypeId<Facet<T1FacetConfiguration>> TYPEID = new FacetTypeId<Facet<T1FacetConfiguration>>("org.xtext.example.mydsl.T1");

	public T1FacetType() {
		super(TYPEID, "org.xtext.example.mydsl.T1", "T1");
		T1Language.INSTANCE.injectMembers(this);
	}
}
