/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea;

import org.xtext.example.mydsl.idea.AbstractT1IdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class T1IdeaModule extends AbstractT1IdeaModule {
}
