/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea;

import com.google.inject.Injector;
import org.xtext.example.mydsl.T1StandaloneSetupGenerated;

@SuppressWarnings("all")
public class T1StandaloneSetupIdea extends T1StandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from T1IdeaModule to Module");
  }
}
