/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.t1;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.t1.Var#getDeclarations <em>Declarations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.t1.T1Package#getVar()
 * @model
 * @generated
 */
public interface Var extends EObject
{
  /**
   * Returns the value of the '<em><b>Declarations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarations</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' attribute list.
   * @see org.xtext.example.mydsl.t1.T1Package#getVar_Declarations()
   * @model unique="false"
   * @generated
   */
  EList<String> getDeclarations();

} // Var
