/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.xtext.example.mydsl.idea.lang.T1Language;

public class T1ExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return T1Language.INSTANCE.<Object> getInstance(clazz);
	}
}
